-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.agendamento
(
    agend_id uuid NOT NULL DEFAULT gen_random_uuid(),
    status_agend_id uuid NOT NULL,
    agend_id_calendar text COLLATE pg_catalog."default" NOT NULL,
    profissional_id uuid NOT NULL,
    clientes_id uuid NOT NULL,
    empresa_id uuid NOT NULL,
    agend_data date NOT NULL,
    agend_origem character varying(20) COLLATE pg_catalog."default" NOT NULL,
    agend_created_at timestamp with time zone NOT NULL DEFAULT now(),
    agend_inicio timestamp with time zone NOT NULL,
    agend_fim timestamp with time zone NOT NULL,
    agend_valor numeric(8, 2) NOT NULL,
    periodo tstzrange GENERATED ALWAYS AS (tstzrange(agend_inicio, agend_fim, '[)'::text)) STORED,
    agend_protocolo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT agendamento_pkey PRIMARY KEY (agend_id),
    CONSTRAINT agendamento_agend_protocolo_key UNIQUE (agend_protocolo)
);

COMMENT ON TABLE public.agendamento
    IS 'Tabela principal de agendamentos com campo calculado de período';

CREATE TABLE IF NOT EXISTS public.agendamento_servico
(
    agend_id uuid NOT NULL,
    servicos_id uuid NOT NULL,
    ordem smallint NOT NULL DEFAULT 1,
    valor_aplicado numeric(10, 2) NOT NULL,
    duracao_aplicada interval NOT NULL,
    observacao text COLLATE pg_catalog."default",
    profissional_id uuid NOT NULL,
    CONSTRAINT pk_agendamento_servico PRIMARY KEY (agend_id, servicos_id, ordem)
);

COMMENT ON TABLE public.agendamento_servico
    IS 'Relacionamento entre agendamentos e serviços';

CREATE TABLE IF NOT EXISTS public.ai_prompt_templates
(
    key text COLLATE pg_catalog."default" NOT NULL,
    version text COLLATE pg_catalog."default" NOT NULL,
    template_text text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ai_prompt_templates_pkey PRIMARY KEY (key, version)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    clientes_id uuid NOT NULL DEFAULT gen_random_uuid(),
    clientes_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    clientes_telefone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    clientes_dt_criacao timestamp with time zone NOT NULL DEFAULT now(),
    empresa_id uuid,
    CONSTRAINT clientes_pkey PRIMARY KEY (clientes_id)
);

COMMENT ON TABLE public.clientes
    IS 'Clientes cadastrados por empresa';

CREATE TABLE IF NOT EXISTS public.contexto_sessao
(
    session_id text COLLATE pg_catalog."default" NOT NULL,
    empresa_id uuid NOT NULL,
    ultimo_intent text COLLATE pg_catalog."default",
    ultimo_action text COLLATE pg_catalog."default",
    ultimo_service_id uuid,
    ultimo_service_name text COLLATE pg_catalog."default",
    ultimo_profissional text COLLATE pg_catalog."default",
    ultimo_date date,
    ultimo_start text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT contexto_sessao_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.contrato
(
    contrato_id uuid NOT NULL DEFAULT gen_random_uuid(),
    empresa_id uuid NOT NULL,
    contrato_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    contrato_valor numeric(8, 2) NOT NULL,
    contrato_nome text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    contrato_periodicidade character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Mensal'::character varying,
    contrato_vigencia_inicio date,
    contrato_proxima_cobranca date,
    CONSTRAINT contrato_pkey PRIMARY KEY (contrato_id)
);

COMMENT ON TABLE public.contrato
    IS 'Contratos com empresas';

CREATE TABLE IF NOT EXISTS public.empresa
(
    empresa_id uuid NOT NULL DEFAULT gen_random_uuid(),
    endereco_id uuid NOT NULL,
    empresa_cfg_id uuid NOT NULL,
    cep character varying(8) COLLATE pg_catalog."default" NOT NULL,
    empresa_nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    empresa_contato character varying(50) COLLATE pg_catalog."default" NOT NULL,
    empresa_dt_criacao timestamp with time zone NOT NULL DEFAULT now(),
    empresa_dt_atualizacao timestamp with time zone NOT NULL DEFAULT now(),
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'ativa'::character varying,
    endereco text COLLATE pg_catalog."default",
    observacoes text COLLATE pg_catalog."default",
    empresa_contato_agente character varying(20) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    CONSTRAINT empresa_pkey PRIMARY KEY (empresa_id)
);

COMMENT ON TABLE public.empresa
    IS 'Entidade raiz para isolamento multi-tenant';

CREATE TABLE IF NOT EXISTS public.empresa_cfg
(
    empresa_cfg_id uuid NOT NULL DEFAULT gen_random_uuid(),
    empresa_cfg_anteced_minutos integer NOT NULL,
    empresa_cfg_interv_minutos integer NOT NULL,
    empresa_cfg_buffer_pre_minutos integer NOT NULL,
    empresa_cfg_buffer_pos_minutos integer NOT NULL,
    empresa_cfg_timezone text COLLATE pg_catalog."default" NOT NULL DEFAULT 'America/Sao_Paulo'::text,
    billing_enabled boolean NOT NULL DEFAULT false,
    empresa_cfg_billing_grace_days integer NOT NULL DEFAULT 3,
    empresa_cfg_nome character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Configuração Padrão'::character varying,
    prompt_key text COLLATE pg_catalog."default" DEFAULT 'prompt_agendamento'::text,
    prompt_version text COLLATE pg_catalog."default" DEFAULT '2025-08-26-01'::text,
    CONSTRAINT empresa_cfg_pkey PRIMARY KEY (empresa_cfg_id)
);

COMMENT ON TABLE public.empresa_cfg
    IS 'Configurações específicas de cada empresa';

CREATE TABLE IF NOT EXISTS public.endereco
(
    endereco_id uuid NOT NULL DEFAULT gen_random_uuid(),
    cep character varying(8) COLLATE pg_catalog."default" NOT NULL,
    logradouro character varying(200) COLLATE pg_catalog."default" NOT NULL,
    numero character varying(20) COLLATE pg_catalog."default",
    complemento character varying(100) COLLATE pg_catalog."default",
    bairro character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(100) COLLATE pg_catalog."default" NOT NULL,
    uf character varying(2) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT endereco_pkey PRIMARY KEY (endereco_id)
);

COMMENT ON TABLE public.endereco
    IS 'Endereços para empresas e profissionais';

CREATE TABLE IF NOT EXISTS public.gcalendar
(
    profissional_id uuid NOT NULL,
    gcalendar_id text COLLATE pg_catalog."default" NOT NULL,
    gcalendar_email citext COLLATE pg_catalog."default",
    CONSTRAINT gcalendar_pkey PRIMARY KEY (gcalendar_id),
    CONSTRAINT uq_gcalendar_id UNIQUE (gcalendar_id)
);

COMMENT ON TABLE public.gcalendar
    IS 'Integração com Google Calendar';

CREATE TABLE IF NOT EXISTS public.horario_det
(
    horario_det_id uuid NOT NULL DEFAULT gen_random_uuid(),
    horario_f_id uuid NOT NULL,
    horario_def smallint NOT NULL,
    horario_def_nome character varying(20) COLLATE pg_catalog."default" NOT NULL,
    horario_det_inicio time(0) without time zone NOT NULL,
    horario_det_fim time(0) without time zone NOT NULL,
    CONSTRAINT horario_det_pkey PRIMARY KEY (horario_det_id),
    CONSTRAINT uq_horario_det_intervalo UNIQUE (horario_f_id, horario_def, horario_det_inicio, horario_det_fim)
);

COMMENT ON TABLE public.horario_det
    IS 'Detalhamento dos horários específicos';

CREATE TABLE IF NOT EXISTS public.horario_f
(
    horario_f_id uuid NOT NULL DEFAULT gen_random_uuid(),
    horario_f_turno character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT horario_f_pkey PRIMARY KEY (horario_f_id)
);

COMMENT ON TABLE public.horario_f
    IS 'Definição de turnos de trabalho';

CREATE TABLE IF NOT EXISTS public.instancia
(
    instancia_id uuid NOT NULL,
    empresa_id uuid NOT NULL,
    instancia_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    instancia_observacao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    instancia_dt_criacao timestamp with time zone NOT NULL DEFAULT now(),
    instancia_dt_atualizacao timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT instancia_pkey PRIMARY KEY (instancia_id)
);

COMMENT ON TABLE public.instancia
    IS 'Instâncias para multi-tenancy';

CREATE TABLE IF NOT EXISTS public.login
(
    login_id uuid NOT NULL,
    nivel_acesso_id uuid NOT NULL,
    empresa_id uuid NOT NULL,
    login citext COLLATE pg_catalog."default" NOT NULL,
    email citext COLLATE pg_catalog."default" NOT NULL,
    senha text COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    nome character varying(120) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT login_pkey PRIMARY KEY (login_id)
);

COMMENT ON TABLE public.login
    IS 'Sistema de autenticação';

CREATE TABLE IF NOT EXISTS public.nivel_acesso
(
    nivel_acesso_id uuid NOT NULL,
    nivel_acesso_ character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT nivel_acesso_pkey PRIMARY KEY (nivel_acesso_id)
);

COMMENT ON TABLE public.nivel_acesso
    IS 'Controle de permissões';

CREATE TABLE IF NOT EXISTS public.profissional
(
    profissional_id uuid NOT NULL DEFAULT gen_random_uuid(),
    empresa_id uuid NOT NULL,
    endereco_id uuid NOT NULL,
    cep character varying(8) COLLATE pg_catalog."default" NOT NULL,
    profissional_nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    profissional_contato character varying(20) COLLATE pg_catalog."default" NOT NULL,
    profissional_dt_criacao timestamp with time zone NOT NULL DEFAULT now(),
    profissional_dt_atualizacao timestamp with time zone NOT NULL DEFAULT now(),
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'ativo'::character varying,
    especialidade character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    observacoes text COLLATE pg_catalog."default",
    CONSTRAINT profissional_pkey PRIMARY KEY (profissional_id)
);

COMMENT ON TABLE public.profissional
    IS 'Profissionais que prestam serviços';

CREATE TABLE IF NOT EXISTS public.profissional_horario
(
    profissional_id uuid NOT NULL,
    horario_f_id uuid NOT NULL,
    CONSTRAINT pk_profissional_horario PRIMARY KEY (profissional_id, horario_f_id)
);

COMMENT ON TABLE public.profissional_horario
    IS 'Horários de trabalho dos profissionais';

CREATE TABLE IF NOT EXISTS public.profissional_servico
(
    servicos_id uuid NOT NULL,
    profissional_id uuid NOT NULL,
    valor_personalizado numeric(10, 2),
    duracao_personalizada interval,
    observacoes character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_profissional_servico PRIMARY KEY (servicos_id, profissional_id)
);

COMMENT ON TABLE public.profissional_servico
    IS 'Serviços que cada profissional pode realizar';

CREATE TABLE IF NOT EXISTS public.servicos
(
    servicos_id uuid NOT NULL DEFAULT gen_random_uuid(),
    servicos_nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    servicos_duracao interval NOT NULL,
    servicos_valor numeric(10, 2) NOT NULL,
    servicos_descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'ativo'::character varying,
    CONSTRAINT servicos_pkey PRIMARY KEY (servicos_id)
);

COMMENT ON TABLE public.servicos
    IS 'Catálogo de serviços oferecidos';

CREATE TABLE IF NOT EXISTS public.status_agend
(
    status_agend_id uuid NOT NULL DEFAULT gen_random_uuid(),
    status_agend_nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT status_agend_pkey PRIMARY KEY (status_agend_id)
);

COMMENT ON TABLE public.status_agend
    IS 'Status dos agendamentos';

ALTER TABLE IF EXISTS public.agendamento
    ADD CONSTRAINT agendamento_clientes_id_foreign FOREIGN KEY (clientes_id)
    REFERENCES public.clientes (clientes_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_agendamento_cliente
    ON public.agendamento(clientes_id);


ALTER TABLE IF EXISTS public.agendamento
    ADD CONSTRAINT agendamento_empresa_id_foreign FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_agendamento_empresa
    ON public.agendamento(empresa_id);


ALTER TABLE IF EXISTS public.agendamento
    ADD CONSTRAINT agendamento_profissional_id_foreign FOREIGN KEY (profissional_id)
    REFERENCES public.profissional (profissional_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.agendamento
    ADD CONSTRAINT agendamento_status_agend_id_foreign FOREIGN KEY (status_agend_id)
    REFERENCES public.status_agend (status_agend_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_agendamento_status
    ON public.agendamento(status_agend_id);


ALTER TABLE IF EXISTS public.agendamento_servico
    ADD CONSTRAINT agendamento_servico_agend_id_fkey FOREIGN KEY (agend_id)
    REFERENCES public.agendamento (agend_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.agendamento_servico
    ADD CONSTRAINT agendamento_servico_servicos_id_fkey FOREIGN KEY (servicos_id)
    REFERENCES public.servicos (servicos_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_agendamento_item_serv
    ON public.agendamento_servico(servicos_id);


ALTER TABLE IF EXISTS public.agendamento_servico
    ADD CONSTRAINT fk_ags_prof FOREIGN KEY (profissional_id)
    REFERENCES public.profissional (profissional_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.agendamento_servico
    ADD CONSTRAINT fk_ags_servico_prof FOREIGN KEY (servicos_id, profissional_id)
    REFERENCES public.profissional_servico (servicos_id, profissional_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT fk_clientes_empresa FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.contrato
    ADD CONSTRAINT contrato_empresa_id_foreign FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ux_contrato_ativo_por_empresa_pt
    ON public.contrato(empresa_id);


ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT empresa_cfg_fk FOREIGN KEY (empresa_cfg_id)
    REFERENCES public.empresa_cfg (empresa_cfg_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT empresa_endereco_id_fkey FOREIGN KEY (endereco_id)
    REFERENCES public.endereco (endereco_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.gcalendar
    ADD CONSTRAINT fk_gcalendar_profissional FOREIGN KEY (profissional_id)
    REFERENCES public.profissional (profissional_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ux_gcalendar_profissional
    ON public.gcalendar(profissional_id);


ALTER TABLE IF EXISTS public.horario_det
    ADD CONSTRAINT horario_det_horario_f_id_foreign FOREIGN KEY (horario_f_id)
    REFERENCES public.horario_f (horario_f_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.instancia
    ADD CONSTRAINT instancia_empresa_id_foreign FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS inst_idx_empresa
    ON public.instancia(empresa_id);


ALTER TABLE IF EXISTS public.login
    ADD CONSTRAINT login_empresa_id_foreign FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.login
    ADD CONSTRAINT login_nivel_acesso_id_foreign FOREIGN KEY (nivel_acesso_id)
    REFERENCES public.nivel_acesso (nivel_acesso_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.profissional
    ADD CONSTRAINT profissional_empresa_id_foreign FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (empresa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS prof_idx_empresa
    ON public.profissional(empresa_id);


ALTER TABLE IF EXISTS public.profissional
    ADD CONSTRAINT profissional_endereco_id_fkey FOREIGN KEY (endereco_id)
    REFERENCES public.endereco (endereco_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.profissional_horario
    ADD CONSTRAINT profissional_horario_horario_f_id_foreign FOREIGN KEY (horario_f_id)
    REFERENCES public.horario_f (horario_f_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ph_idx_horario
    ON public.profissional_horario(horario_f_id);


ALTER TABLE IF EXISTS public.profissional_horario
    ADD CONSTRAINT profissional_horario_profissional_id_foreign FOREIGN KEY (profissional_id)
    REFERENCES public.profissional (profissional_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.profissional_servico
    ADD CONSTRAINT profissional_servico_profissional_id_foreign FOREIGN KEY (profissional_id)
    REFERENCES public.profissional (profissional_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ps_idx_prof
    ON public.profissional_servico(profissional_id);


ALTER TABLE IF EXISTS public.profissional_servico
    ADD CONSTRAINT profissional_servico_servicos_id_foreign FOREIGN KEY (servicos_id)
    REFERENCES public.servicos (servicos_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
